### ISSUE TITLE
Can I get credentials to use the API?

### ISSUE THREAD

**Issue by DenisSouth** [Affectiva/emotion-api-python#17]
I already wrote to affectiva com/contact-us/ but no one reply me

**Comment by ForestJay** [comment]
Hi Denis, we need your contact info to discuss. If you don't want to share here you can email my user ( forest) to affectiva.com .

**Comment by AhmedARadwan** [comment]
I'm having the same problem. @ForestJay could you help me with that?

**Comment by ForestJay** [comment]
Hi @AhmedARadwan , Can you send your contact info to me ( forest.handford+GH@affectiva.com ) and I'll have the team get in touch with you.
